import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const iranSans = localFont({src:"../public/fonts/IRANSansX-Regular.woff"});

export const metadata: Metadata = {
  title: "JSK Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={iranSans.className}>{children}</body>
    </html>
  );
}
