import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/components/header";
import Footer from "@/components/footer";
// import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const iranSans = localFont({ src: "../public/fonts/IRANSansX-Regular.woff" });

export const metadata: Metadata = {
  title: "JSK Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={iranSans.className}>
        {/* <AntdRegistry> */}
        <Header />
        {children}
        <Footer />
        {/* </AntdRegistry> */}
      </body>
    </html>
  );
}
